name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
    
    - name: Build App
      run: |
        chmod +x build_app.sh
        ./build_app.sh
        
    - name: Create Basic DMG
      run: |
        # Install create-dmg
        brew install create-dmg
        
        # Create a basic DMG without custom graphics
        create-dmg \
          --volname "CleanYourMac" \
          --window-size 500 300 \
          --app-drop-link 350 130 \
          "dist/CleanYourMac.dmg" \
          "dist/CleanYourMac.app"
      
    - name: Create ZIP Archive (Alternative)
      run: |
        cd dist
        zip -r CleanYourMac.zip CleanYourMac.app
    
    - name: Create Prerelease
      id: create_prerelease
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/CleanYourMac.dmg
          dist/CleanYourMac.zip
        tag_name: latest
        name: "Latest Development Build"
        body: "This is a pre-release build from the main branch and may be unstable."
        prerelease: true
        draft: false